-- Migration: Add GIN (Generalized Inverted Index) for full-text search on users
-- This replaces the ILIKE sequential scan used by searchUsers with a fast FTS index.
-- plainto_tsquery() is used in application code to prevent tsvector injection.
--
-- NOTE: CREATE INDEX CONCURRENTLY is intentionally NOT used here because Prisma
-- executes migrations inside an implicit transaction, and CONCURRENTLY is invalid
-- inside a transaction block. The non-concurrent form locks the table only briefly
-- for index creation; run this during a low-traffic window on production.

-- GIN index for full-text search across username and fullName.
-- Uses the 'simple' dictionary to avoid language-specific stemming (Indonesian names).
-- FIX: Column names use camelCase as generated by Prisma (no @map annotation).
CREATE INDEX IF NOT EXISTS idx_users_fts_search
  ON users USING GIN (
    to_tsvector('simple', coalesce(username, '') || ' ' || "fullName")
  );

-- Partial index on lower(username) to accelerate prefix-ranking in ORDER BY
-- (CASE WHEN lower(username) LIKE 'query%') for active, non-banned users.
-- FIX: Column names use Prisma camelCase conventions.
CREATE INDEX IF NOT EXISTS idx_users_username_lower
  ON users (lower(username))
  WHERE "isActive" = true AND "isBanned" = false AND "deletedAt" IS NULL;
