// Auth
export const USERNAME_TAKEN = 'USERNAME_TAKEN';
export const USERNAME_INVALID_FORMAT = 'USERNAME_INVALID_FORMAT';
export const USERNAME_RESERVED = 'USERNAME_RESERVED';
export const USERNAME_ALREADY_SET = 'USERNAME_ALREADY_SET';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
export const PHONE_NOT_VERIFIED = 'PHONE_NOT_VERIFIED';
export const TOKEN_INVALID_OR_EXPIRED = 'TOKEN_INVALID_OR_EXPIRED';
export const ACCOUNT_BANNED = 'ACCOUNT_BANNED';
export const ACCOUNT_LOCKED = 'ACCOUNT_LOCKED';
export const ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const TEMP_TOKEN_EXPIRED = 'TEMP_TOKEN_EXPIRED';
export const INVALID_2FA_CODE = 'INVALID_2FA_CODE';
export const INSUFFICIENT_TOKEN_SCOPE = 'INSUFFICIENT_TOKEN_SCOPE';
export const TWO_FA_ALREADY_ENABLED = 'TWO_FA_ALREADY_ENABLED';
export const TWO_FA_NOT_ENABLED = 'TWO_FA_NOT_ENABLED';
export const PASSWORD_WRONG = 'PASSWORD_WRONG';
export const CURRENT_PASSWORD_WRONG = 'CURRENT_PASSWORD_WRONG';
export const PASSWORD_SAME_AS_OLD = 'PASSWORD_SAME_AS_OLD';
export const PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK';
export const PASSWORDS_DO_NOT_MATCH = 'PASSWORDS_DO_NOT_MATCH';
export const OTP_INVALID = 'OTP_INVALID';
export const SESSION_REVOKED = 'SESSION_REVOKED';

// User / KYC
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const KYC_ALREADY_PENDING = 'KYC_ALREADY_PENDING';
export const KYC_ALREADY_APPROVED = 'KYC_ALREADY_APPROVED';
export const KYC_DUPLICATE_NIK = 'KYC_DUPLICATE_NIK';
export const KYC_COOLDOWN_ACTIVE = 'KYC_COOLDOWN_ACTIVE';

// Orders
export const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
export const INVALID_ORDER_STATUS = 'INVALID_ORDER_STATUS';
export const NOT_ORDER_PARTICIPANT = 'NOT_ORDER_PARTICIPANT';
export const CANNOT_ORDER_SELF = 'CANNOT_ORDER_SELF';
export const USER_BLOCKED = 'USER_BLOCKED';
export const BUYER_PAY_AMOUNT_MISMATCH = 'BUYER_PAY_AMOUNT_MISMATCH';
export const IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED';
export const OPTIMISTIC_LOCK_CONFLICT = 'OPTIMISTIC_LOCK_CONFLICT';
export const ESCROW_LIMIT_EXCEEDED = 'ESCROW_LIMIT_EXCEEDED';
export const ESCROW_LOCK_MISSING = 'ESCROW_LOCK_MISSING';

// Wallet
export const INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE';
export const DAILY_TOPUP_LIMIT_EXCEEDED = 'DAILY_TOPUP_LIMIT_EXCEEDED';
export const DAILY_WITHDRAW_LIMIT_EXCEEDED = 'DAILY_WITHDRAW_LIMIT_EXCEEDED';
export const BELOW_MINIMUM_WITHDRAW = 'BELOW_MINIMUM_WITHDRAW';
export const PAYOUT_FAILED = 'PAYOUT_FAILED';
export const KYC_REQUIRED = 'KYC_REQUIRED';
export const KYC_REQUIRED_FOR_WITHDRAW = 'KYC_REQUIRED_FOR_WITHDRAW';

// Disputes
export const DISPUTE_NOT_FOUND = 'DISPUTE_NOT_FOUND';
export const NOT_DISPUTE_PARTICIPANT = 'NOT_DISPUTE_PARTICIPANT';
export const DISPUTE_ALREADY_EXISTS = 'DISPUTE_ALREADY_EXISTS';
export const DISPUTE_CALL_NOT_FOUND = 'DISPUTE_CALL_NOT_FOUND';
export const DISPUTE_CALL_ALREADY_ACTIVE = 'DISPUTE_CALL_ALREADY_ACTIVE';
export const DISPUTE_CALL_INVALID_STATUS = 'DISPUTE_CALL_INVALID_STATUS';
export const DISPUTE_NOT_ACTIVE = 'DISPUTE_NOT_ACTIVE';

// Referral
export const REFERRAL_SELF = 'REFERRAL_SELF';
export const REFERRAL_ALREADY_APPLIED = 'REFERRAL_ALREADY_APPLIED';
export const REFERRAL_CODE_NOT_FOUND = 'REFERRAL_CODE_NOT_FOUND';

// Subscriptions
export const SUBSCRIPTION_ALREADY_ACTIVE = 'SUBSCRIPTION_ALREADY_ACTIVE';
export const NO_ACTIVE_SUBSCRIPTION = 'NO_ACTIVE_SUBSCRIPTION';
export const SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND';
export const SUBSCRIPTION_NOT_OWNED = 'SUBSCRIPTION_NOT_OWNED';
export const SUBSCRIPTION_NOT_PENDING = 'SUBSCRIPTION_NOT_PENDING';

// Settings / Social
export const CANNOT_BLOCK_SELF = 'CANNOT_BLOCK_SELF';
export const USER_ALREADY_BLOCKED = 'USER_ALREADY_BLOCKED';
export const USER_NOT_BLOCKED = 'USER_NOT_BLOCKED';
export const CANNOT_REPORT_SELF = 'CANNOT_REPORT_SELF';
export const CANNOT_FOLLOW_SELF = 'CANNOT_FOLLOW_SELF';
export const CANNOT_FAVORITE_SELF = 'CANNOT_FAVORITE_SELF';
export const ALREADY_FAVORITED = 'ALREADY_FAVORITED';
export const NOT_FAVORITED = 'NOT_FAVORITED';
export const CANNOT_ASK_SELF = 'CANNOT_ASK_SELF';
export const ALREADY_FOLLOWING = 'ALREADY_FOLLOWING';
export const NOT_FOLLOWING = 'NOT_FOLLOWING';
export const USERNAME_CHANGE_COOLDOWN = 'USERNAME_CHANGE_COOLDOWN';
export const DUPLICATE_REPORT = 'DUPLICATE_REPORT';

// Upload
export const INVALID_FILE_TYPE = 'INVALID_FILE_TYPE';
export const FILE_TOO_LARGE = 'FILE_TOO_LARGE';
export const MIME_TYPE_MISMATCH = 'MIME_TYPE_MISMATCH';
export const FILE_NOT_CONFIRMED = 'FILE_NOT_CONFIRMED';
export const FILE_NOT_FOUND_OR_EXPIRED = 'FILE_NOT_FOUND_OR_EXPIRED';

// Vouchers
export const VOUCHER_CODE_TAKEN = 'VOUCHER_CODE_TAKEN';
export const VOUCHER_NOT_FOUND = 'VOUCHER_NOT_FOUND';
export const VOUCHER_EXPIRED = 'VOUCHER_EXPIRED';
export const VOUCHER_USAGE_LIMIT_REACHED = 'VOUCHER_USAGE_LIMIT_REACHED';
export const VOUCHER_NOT_APPLICABLE = 'VOUCHER_NOT_APPLICABLE';

// Admin
export const ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND';
export const INSUFFICIENT_ADMIN_ROLE = 'INSUFFICIENT_ADMIN_ROLE';
export const INVALID_STATUS = 'INVALID_STATUS';
export const WEBHOOK_NOT_FOUND = 'WEBHOOK_NOT_FOUND';
export const WEBHOOK_ALREADY_PROCESSED = 'WEBHOOK_ALREADY_PROCESSED';
export const WEBHOOK_MAX_RETRY_EXCEEDED = 'WEBHOOK_MAX_RETRY_EXCEEDED';
export const INVALID_DATE_RANGE = 'INVALID_DATE_RANGE';
export const DATE_RANGE_TOO_LARGE = 'DATE_RANGE_TOO_LARGE';
export const INVALID_FORMAT = 'INVALID_FORMAT';

// Ratings
export const RATING_WINDOW_CLOSED = 'RATING_WINDOW_CLOSED';
export const ALREADY_RATED = 'ALREADY_RATED';
export const RATING_NOT_FOUND = 'RATING_NOT_FOUND';
export const NOT_RATING_GIVER = 'NOT_RATING_GIVER';
export const RATING_BLOCKED_FORCE_COMPLETED = 'RATING_BLOCKED_FORCE_COMPLETED';

// Notifications
export const NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND';
export const NOTIFICATION_NOT_OWNED = 'NOTIFICATION_NOT_OWNED';

// Sessions
export const SESSION_NOT_FOUND = 'SESSION_NOT_FOUND';
export const SESSION_NOT_OWNED = 'SESSION_NOT_OWNED';
export const SESSION_ALREADY_REVOKED = 'SESSION_ALREADY_REVOKED';

// Bank
export const BANK_ACCOUNT_NOT_FOUND = 'BANK_ACCOUNT_NOT_FOUND';
export const BANK_ACCOUNT_NOT_VERIFIED = 'BANK_ACCOUNT_NOT_VERIFIED';
export const BANK_ACCOUNT_NOT_OWNED = 'BANK_ACCOUNT_NOT_OWNED';
export const CANNOT_DELETE_PRIMARY_BANK = 'CANNOT_DELETE_PRIMARY_BANK';
export const MAX_BANK_ACCOUNTS_REACHED = 'MAX_BANK_ACCOUNTS_REACHED';
export const BANK_ACCOUNT_HAS_PENDING_WITHDRAWAL = 'BANK_ACCOUNT_HAS_PENDING_WITHDRAWAL';

// Generic
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const FORBIDDEN = 'FORBIDDEN';
export const NOT_FOUND = 'NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
export const RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
export const IDEMPOTENCY_KEY_IN_USE = 'IDEMPOTENCY_KEY_IN_USE';
export const IDEMPOTENCY_KEY_REUSE = 'IDEMPOTENCY_KEY_REUSE';
export const IDEMPOTENCY_SERVICE_UNAVAILABLE = 'IDEMPOTENCY_SERVICE_UNAVAILABLE';

export const INVALID_PAYMENT_METHOD = 'INVALID_PAYMENT_METHOD';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';

export const PASSWORD_RECENTLY_USED = 'PASSWORD_RECENTLY_USED';

export const ACTIVE_ORDERS_PRESENT = 'ACTIVE_ORDERS_PRESENT';
export const ESCROW_BALANCE_PRESENT = 'ESCROW_BALANCE_PRESENT';
export const WALLET_BALANCE_PRESENT = 'WALLET_BALANCE_PRESENT';

export const BADGE_NOT_FOUND = 'BADGE_NOT_FOUND';
export const BADGE_NAME_TAKEN = 'BADGE_NAME_TAKEN';
export const REPORT_NOT_FOUND = 'REPORT_NOT_FOUND';
export const REPORT_ALREADY_RESOLVED = 'REPORT_ALREADY_RESOLVED';
export const KYC_NOT_FOUND = 'KYC_NOT_FOUND';
export const WALLET_NOT_FOUND = 'WALLET_NOT_FOUND';
export const WALLET_LOCKED = 'WALLET_LOCKED';
export const MFA_REQUIRED = 'MFA_REQUIRED';
export const INVALID_MFA = 'INVALID_MFA';
export const MFA_NOT_CONFIGURED = 'MFA_NOT_CONFIGURED';
export const USER_ALREADY_BANNED = 'USER_ALREADY_BANNED';
export const BADGE_ALREADY_AWARDED = 'BADGE_ALREADY_AWARDED';
export const BADGE_HAS_AWARDS = 'BADGE_HAS_AWARDS';
export const USER_BADGE_NOT_FOUND = 'USER_BADGE_NOT_FOUND';
export const INVALID_SPLIT_PERCENT = 'INVALID_SPLIT_PERCENT';
export const EXTENSION_REQUEST_ALREADY_PENDING = 'EXTENSION_REQUEST_ALREADY_PENDING';
export const EXTENSION_LIMIT_REACHED = 'EXTENSION_LIMIT_REACHED';
export const DISPUTE_CLOSED_FOR_EVIDENCE = 'DISPUTE_CLOSED_FOR_EVIDENCE';

export const ORDER_PAYMENT_EXPIRED = 'ORDER_PAYMENT_EXPIRED';

export const ORDER_LINK_NOT_FOUND = 'ORDER_LINK_NOT_FOUND';
export const ORDER_LINK_EXPIRED = 'ORDER_LINK_EXPIRED';
export const ORDER_LINK_ALREADY_USED = 'ORDER_LINK_ALREADY_USED';
export const ORDER_LINK_OWN = 'ORDER_LINK_OWN';
export const DELIVERY_PROOF_NOT_FOUND = 'DELIVERY_PROOF_NOT_FOUND';
export const DELIVERY_PROOF_ALREADY_EXISTS = 'DELIVERY_PROOF_ALREADY_EXISTS';
export const DELIVERY_PROOF_ALREADY_REVIEWED = 'DELIVERY_PROOF_ALREADY_REVIEWED';
export const NOT_RATING_RECEIVER = 'NOT_RATING_RECEIVER';
export const REPLY_ALREADY_EXISTS = 'REPLY_ALREADY_EXISTS';
export const QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND';
export const CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND';
export const CAMPAIGN_ACTIVE = 'CAMPAIGN_ACTIVE';
export const INVALID_CAMPAIGN_DATES = 'INVALID_CAMPAIGN_DATES';
export const SCHEDULED_WITHDRAWAL_NOT_FOUND = 'SCHEDULED_WITHDRAWAL_NOT_FOUND';
export const SCHEDULE_NOT_FOUND = 'SCHEDULE_NOT_FOUND';
export const SCHEDULE_ALREADY_EXISTS = 'SCHEDULE_ALREADY_EXISTS';
export const INVALID_SCHEDULE = 'INVALID_SCHEDULE';
export const COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';
export const UPLOAD_STORAGE_UNAVAILABLE = 'UPLOAD_STORAGE_UNAVAILABLE';

export const WEBHOOK_UNAUTHORIZED_IP = 'WEBHOOK_UNAUTHORIZED_IP';
export const DAILY_REPORT_LIMIT_EXCEEDED = 'DAILY_REPORT_LIMIT_EXCEEDED';
export const INVALID_SOCIAL_LINK_URL = 'INVALID_SOCIAL_LINK_URL';

export const FILE_REQUIRED = 'FILE_REQUIRED';
export const TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND';
export const TEMPLATE_NOT_OWNED = 'TEMPLATE_NOT_OWNED';
export const TEMPLATE_LIMIT_REACHED = 'TEMPLATE_LIMIT_REACHED';
export const FAQ_NOT_FOUND = 'FAQ_NOT_FOUND';
export const SEARCH_INVALID_TYPES = 'SEARCH_INVALID_TYPES';
export const CARD_TOKEN_REQUIRED = 'CARD_TOKEN_REQUIRED';
export const RECEIPT_NOT_AVAILABLE = 'RECEIPT_NOT_AVAILABLE';
export const REFERRAL_KYC_REQUIRED = 'REFERRAL_KYC_REQUIRED';
export const REFERRAL_TRANSACTION_REQUIRED = 'REFERRAL_TRANSACTION_REQUIRED';
export const COUNTERPART_SUSPENDED = 'COUNTERPART_SUSPENDED';
export const OTP_TX_MISMATCH = 'OTP_TX_MISMATCH';
export const NOT_ASSIGNED_ADMIN = 'NOT_ASSIGNED_ADMIN';
export const DISPUTE_AMOUNT_EXCEEDS_ESCROW = 'DISPUTE_AMOUNT_EXCEEDS_ESCROW';
export const ESCROW_BALANCE_MISMATCH = 'ESCROW_BALANCE_MISMATCH';
export const DISPUTE_ALREADY_RESOLVED = 'DISPUTE_ALREADY_RESOLVED';
export const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
export const TOKEN_REQUIRED = 'TOKEN_REQUIRED';
export const CAPTCHA_FAILED = 'CAPTCHA_FAILED';
export const CAPTCHA_EXPIRED = 'CAPTCHA_EXPIRED';
export const CAPTCHA_REQUIRED = 'CAPTCHA_REQUIRED';

export const ORDER_COUNTERPART_COOLDOWN = 'ORDER_COUNTERPART_COOLDOWN';
export const INVALID_CANCEL_REASON = 'INVALID_CANCEL_REASON';
export const INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION';
export const EXTENSION_RATE_LIMITED = 'EXTENSION_RATE_LIMITED';
export const DELIVERY_PROOF_REQUIRED = 'DELIVERY_PROOF_REQUIRED';

export const CHAT_ROOM_CLOSED = 'CHAT_ROOM_CLOSED';
export const INVALID_IDEMPOTENCY_KEY = 'INVALID_IDEMPOTENCY_KEY';
export const UPLOAD_ALREADY_CONFIRMED = 'UPLOAD_ALREADY_CONFIRMED';
export const FILE_ACCESS_DENIED = 'FILE_ACCESS_DENIED';
export const UPLOAD_NOT_CONFIRMED = 'UPLOAD_NOT_CONFIRMED';

export const KYC_REVOKED = 'KYC_REVOKED';
export const KYC_USE_RESUBMIT = 'KYC_USE_RESUBMIT';
export const KYC_MAX_ATTEMPTS_REACHED = 'KYC_MAX_ATTEMPTS_REACHED';

export const CANNOT_TRANSFER_SELF = 'CANNOT_TRANSFER_SELF';
export const RECIPIENT_NOT_FOUND = 'RECIPIENT_NOT_FOUND';
export const RECIPIENT_KYC_REQUIRED = 'RECIPIENT_KYC_REQUIRED';
export const SENDER_KYC_REQUIRED = 'SENDER_KYC_REQUIRED';
export const DAILY_TRANSFER_LIMIT_EXCEEDED = 'DAILY_TRANSFER_LIMIT_EXCEEDED';
export const BELOW_MINIMUM_TRANSFER = 'BELOW_MINIMUM_TRANSFER';
export const ABOVE_MAXIMUM_TRANSFER = 'ABOVE_MAXIMUM_TRANSFER';
export const ABOVE_MAXIMUM_WITHDRAW = 'ABOVE_MAXIMUM_WITHDRAW';
export const PIN_RATE_LIMITED = 'PIN_RATE_LIMITED';
export const PIN_IP_RATE_LIMITED = 'PIN_IP_RATE_LIMITED';
export const RECIPIENT_WALLET_LOCKED = 'RECIPIENT_WALLET_LOCKED';

// Thrown when a password-reset / email-change flow is invoked but SMTP is not configured
// (`auth.service.ts:1853`, `:1974`, `admin-users.service.ts:572`). Those three sites already
// emit the string literal; exporting it here keeps it discoverable alongside every other
// client-facing code and lets the clients map it to a translated message.
export const EMAIL_NOT_CONFIGURED = 'EMAIL_NOT_CONFIGURED';
