/**
 * 20.1 Lintas Modul Enum Reasons - unified reason codes for cancel/dispute/report
 */

export enum OrderCancelReason {
  CHANGED_MIND = 'CHANGED_MIND',
  WRONG_DETAILS = 'WRONG_DETAILS',
  DUPLICATE_ORDER = 'DUPLICATE_ORDER',
  MUTUAL_AGREEMENT = 'MUTUAL_AGREEMENT',
  COUNTERPART_UNRESPONSIVE = 'COUNTERPART_UNRESPONSIVE',
  OTHER = 'OTHER',
}

export enum DisputeCategoryReason {
  ITEM_NOT_RECEIVED = 'ITEM_NOT_RECEIVED',
  ITEM_NOT_AS_DESCRIBED = 'ITEM_NOT_AS_DESCRIBED',
  DAMAGED_ITEM = 'DAMAGED_ITEM',
  WRONG_ITEM = 'WRONG_ITEM',
  SERVICE_NOT_RENDERED = 'SERVICE_NOT_RENDERED',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  FRAUD = 'FRAUD',
  OTHER = 'OTHER',
}

export enum UserReportReason {
  SPAM = 'SPAM',
  FRAUD = 'FRAUD',
  HARASSMENT = 'HARASSMENT',
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  FAKE_ACCOUNT = 'FAKE_ACCOUNT',
  OTHER = 'OTHER',
}

export enum ShowcaseReportReason {
  SPAM = 'SPAM',
  INAPPROPRIATE = 'INAPPROPRIATE',
  COPYRIGHT = 'COPYRIGHT',
  FRAUD = 'FRAUD',
  OTHER = 'OTHER',
}
