-- Add public cancellation reasons while preserving legacy values.
ALTER TYPE "OrderCancelReason" ADD VALUE IF NOT EXISTS 'CHANGED_MIND';
ALTER TYPE "OrderCancelReason" ADD VALUE IF NOT EXISTS 'WRONG_DETAILS';
ALTER TYPE "OrderCancelReason" ADD VALUE IF NOT EXISTS 'DUPLICATE_ORDER';
ALTER TYPE "OrderCancelReason" ADD VALUE IF NOT EXISTS 'MUTUAL_AGREEMENT';
ALTER TYPE "OrderCancelReason" ADD VALUE IF NOT EXISTS 'COUNTERPART_UNRESPONSIVE';
ALTER TYPE "OrderCancelReason" ADD VALUE IF NOT EXISTS 'OTHER';
